# Generated by Django 5.0.6 on 2024-05-18 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="approved_comments",
            new_name="approved_comment",
        ),
        migrations.RenameField(
            model_name="post", old_name="create_date", new_name="created_date",
        ),
        migrations.RemoveField(model_name="comment", name="create_date",),
        migrations.AddField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
